# Generated by Django 4.1.4 on 2022-12-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofeature', '0002_alter_task_labels_alter_task_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
